[package]
name = "puzzle-dont-look-up"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prompt = { git = "https://github.com/kobigurk/zkhack-prompt" }
rand = "0.8"
sha2 = "0.10"